version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - sqlite-db:/app/sqlite-db
    ports:
      - "8000:8000"

  # frontend:
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

volumes:
  sqlite-db:
